FROM nvcr.io/nvidia/l4t-base:35.3.1 
MAINTAINER forsrc@gmail.com


RUN apt-get -q update

RUN apt-get install -y curl

RUN curl -k https://get.docker.com -o get-docker.sh
RUN chmod +x get-docker.sh
RUN ./get-docker.sh

RUN apt-get clean autoclean && apt-get autoremove --yes && rm -rf /var/lib/{apt,dpkg,cache,log}/

RUN systemctl enable docker

VOLUME /var/lib/docker

EXPOSE 2375 2376

CMD ["/sbin/init"]
