FROM forsrc/dind:ubuntu
MAINTAINER forsrc@gmail.com

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update

#RUN apt-get install -y apt-transport-https curl
RUN curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
RUN echo "deb https://apt.kubernetes.io/ kubernetes-xenial main" > /etc/apt/sources.list.d/kubernetes.list
RUN apt-get update
RUN apt-get install -y kubelet kubeadm kubectl

RUN apt-get clean autoclean && apt-get autoremove --yes && rm -rf /var/lib/{apt,dpkg,cache,log}/

RUN systemctl enable docker
RUN systemctl enable kubelet

VOLUME /var/lib/docker
VOLUME /var/lib/kubelet

EXPOSE 6443 10248

CMD [ "/usr/sbin/init"]
