FROM forsrc/dind:jetson
MAINTAINER forsrc@gmail.com


ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update
RUN apt-get install -y apt-transport-https ca-certificates curl
RUN mkdir -p /etc/apt/keyrings
RUN curl -fsSL https://packages.cloud.google.com/apt/doc/apt-key.gpg | gpg --dearmor -o /etc/apt/keyrings/kubernetes-archive-keyring.gpg
RUN echo "deb [signed-by=/etc/apt/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" \
    tee /etc/apt/sources.list.d/kubernetes.list  > /dev/null

RUN apt-get update
RUN apt-get install -y kubelet kubeadm kubectl

RUN apt-get clean autoclean && apt-get autoremove --yes && rm -rf /var/lib/{apt,dpkg,cache,log}/

RUN systemctl enable docker
RUN systemctl enable containerd
RUN systemctl enable kubelet

VOLUME /var/lib/docker
VOLUME /var/lib/kubelet

EXPOSE 6443 10248

CMD [ "/usr/sbin/init"]
